apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-plane
  namespace: ${apps_namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-plane
subjects:
  - kind: ServiceAccount
    name: control-plane
    namespace: ${namespace}
